name: tower_metadata
dependencies:
- binstar=0.10.3=py27_0
- clyent=0.3.4=py27_0
- curl=7.38.0=0
- hdf5=1.8.14=0
- libnetcdf=4.3.2=1
- netcdf4=1.1.6=np19py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py27_1
- pip=6.1.1=py27_0
- python=2.7.9=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.2=py27_0
- pyyaml=3.11=py27_0
- readline=6.2=2
- requests=2.6.2=py27_0
- setuptools=15.1=py27_1
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- zlib=1.2.8=0
- pip:
  - dropbox==2.2.0
  - fake-factory==0.5.0
  - flask==0.10.1
  - flask-bootstrap==3.3.2.1
  - flask-bower==1.1.1
  - flask-moment==0.4.0
  - flask-mongoengine==0.7.1
  - flask-script==2.0.5
  - flask-wtf==0.11
  - itsdangerous==0.24
  - jinja2==2.7.3
  - markupsafe==0.23
  - mongoengine==0.9.0
  - pyandoc==0.0.1
  - pymongo==3.0.1
  - urllib3==1.10.3
  - waitress==0.8.9
  - werkzeug==0.10.4
  - wtforms==2.0.2
  - xray==0.4.1

