name: tower_metadata
dependencies:
- binstar=0.10.3=py27_0
- clyent=0.3.4=py27_0
- curl=7.38.0=0
- cffi==1.1.2
- hdf5=1.8.14=0
- libnetcdf=4.3.2=1
- netcdf4=1.1.6=np19py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py27_1
- pip=6.1.1=py27_0
- python=2.7.9=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.2=py27_0
- pyyaml=3.11=py27_0
- readline=6.2=2
- requests=2.6.2=py27_0
- setuptools=15.1=py27_1
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- zlib=1.2.8=0
- xarray==0.7.2
- pip:
  - amqp==1.4.9
  - anyjson==0.3.3
  - billiard==3.3.0.23
  - celery==3.1.23
  - cryptography==0.9.1
  - docopt==0.6.2
  - enum34==1.0.4
  - dropbox==8.9.0
  - fake-factory==0.5.0
  - flask==0.10.1
  - flask-bootstrap==3.3.2.1
  - flask-bower==1.1.1
  - flask-mailgun==0.4
  - flask-moment==0.4.0
  - flask-login==0.3.2
  - flask-mongoengine==0.7.1
  - flask-script==2.0.5
  - flask-wtf==0.11
  - idna==2.0
  - ipaddress==1.0.7
  - itsdangerous==0.24
  - jinja2==2.7.3
  - kombu==3.0.35
  - mglob==0.4
  - markupsafe==0.23
  - mongoengine==0.9.0
  - ndg-httpsclient==0.4.0
  - nose==1.3.6
  - pip-pop==0.1.0
  - pyOpenSSL==0.15.1
  - pyandoc==0.0.1
  - pyasn1==0.1.8
  - pycparser==2.14
  - pymongo==2.8.0
  - python-dateutil==2.4.2
  - pytz==2015.2
  - redis==2.10.5
  - requests==2.7.0
  - six==1.9.0
  - slacker==0.6.2
  - urllib3==1.10.3
  - waitress==0.8.9
  - werkzeug==0.10.4
  - wtforms==2.0.2
  - wsgiref==0.1.2


